name: generator-build

on:
  push: 

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Switch clang
      run: |
        brewPath="$(brew --prefix llvm)/bin"
        echo $brewPath
        echo "::add-path::$brewPath"
    - name: Debug
      run: |
        clang --version
        clang++ --version
    - name: configure
      run: |
        export CC="/usr/local/opt/llvm/bin/clang"
        export CXX="$CC++"
        cmake CMakeLists.txt
    - name: make
      run: |
        xcode-select --install
        make CXX=/usr/local/opt/llvm/bin/clang++ LDFLAGS=-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib CPPFLAGS=-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/
