name: generator-build

on:
  push: 

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Switch clang
      run: |
        brew remove llvm
        brew install llvm@7
        ls /usr/local/opt/
        brewPath="$(brew --prefix llvm@7)/bin"
        echo $brewPath
        echo "::add-path::$brewPath"
    - name: Debug
      run: |
        clang --version
        clang++ --version
    - name: configure
      run: |
        export CC="/usr/local/opt/llvm@7/bin/clang"
        export CXX="$CC++"
        export CPPFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm@7/include/c++/v1/" 
        export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm@7/lib"
        cmake CMakeLists.txt
    - name: make
      run: |
        make CXX=/usr/local/opt/llvm@7/bin/clang++ LDFLAGS=-L/usr/local/opt/llvm@7/lib -Wl,-rpath,/usr/local/opt/llvm@7/lib CPPFLAGS=-I/usr/local/opt/llvm@7/include -I/usr/local/opt/llvm@7/include/c++/v1/
