name: generator-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Exports
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        export CMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path)
        echo $CMAKE_OSX_SYSROOT
    - name: configure
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        export CMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path)
        echo $CMAKE_OSX_SYSROOT
        cmake CMakeLists.txt 
    - name: make
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.9
        export CMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path)
        echo $CMAKE_OSX_SYSROOT
        clang --version
        make
